version: '3.8'

networks:
  laravel:
    
services:
  nginx:
    image: nginx:1.18.0-alpine
    ports: 
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: premier_projet
    ports:
      - "3306:3306"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8000:80"
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel